### ISSUE TITLE
[BUG] Projects using unit testing on incremental models fail with `error: dbt9002: Invalid given input: this`

### ISSUE THREAD

**Issue by jimioksman** [dbt-labs/dbt-fusion#150]
**Describe the bug**
Running a command that parses a project that uses unit testing on incremental models fails with `error: dbt9002: Invalid given input: this`

**What version of dbt Fusion is this bug in? (find out by running `dbt --version`)**
`dbt-fusion 2.0.0-beta.14`

**Is this a discrepancy between the dbt Fusion Engine and dbt Core? Check one.**
- [x] YES
- [ ] NO

**To Reproduce**
Have an incremental model, which uses unit testing.

For example, model yaml:

```yml
unit_tests:
  - name: my_incremental_model_test
    model: my_incremental_model
    overrides:
      macros:
        is_incremental: true
    given:
      - input: this
```

Run any dbt command that parses the project: run, compile, parse, etc.

Produces the following error:
`error: dbt9002: Invalid given input: this`

**Expected behavior**
Project parses successfully without errors.

**Operating System and CPU Type (please complete the following information):**
* Linux
* X86

**Comment by matt-winkler** [comment]
On `2.0.0-beta.43`, I'm seeing the unit tests pass successfully in this situation. However, the LSP is still sending an "invalid input: this" message in the "Problems" tab.

```unit_tests:
  - name: test_orders_incremental_inserts_only_new_orders
    description: "Test that orders_incremental only inserts new orders during an incremental run."
    model: orders_incremental
    overrides:
      macros:
        # unit test this model in "incremental" mode
        is_incremental: true
    given:
      - input: ref('stg_orders')
        rows:
          - { order_id: 1, customer_id: 'A', subtotal: 10.0, tax_paid: 1.0, order_total: 11.0, order_date: '2024-01-01' }
          - { order_id: 2, customer_id: 'B', subtotal: 20.0, tax_paid: 2.0, order_total: 22.0, order_date: '2024-01-02' }
          - { order_id: 3, customer_id: 'C', subtotal: 30.0, tax_paid: 3.0, order_total: 33.0, order_date: '2024-01-03' }
      - input: this
        rows:
          - { order_id: 1, customer_id: 'A', subtotal: 10.0, tax_paid: 1.0, order_total: 11.0, order_date: '2024-01-01' }
    expect:
      rows:
        - { order_id: 2, customer_id: 'B', subtotal: 20.0, tax_paid: 2.0, order_total: 22.0, order_date: '2024-01-02' }
        - { order_id: 3, customer_id: 'C', subtotal: 30.0, tax_paid: 3.0, order_total: 33.0, order_date: '2024-01-03' } 
  
  - name: test_orders_incremental_full_refresh_inserts_all_orders
    description: "Test that orders_incremental inserts all orders during a full refresh."
    model: orders_incremental
    overrides:
      macros:
        # unit test this model in "incremental" mode
        is_incremental: false
    given:
      - input: ref('stg_orders')
        rows:
          - { order_id: 1, customer_id: 'A', subtotal: 10.0, tax_paid: 1.0, order_total: 11.0, order_date: '2024-01-01' }
          - { order_id: 2, customer_id: 'B', subtotal: 20.0, tax_paid: 2.0, order_total: 22.0, order_date: '2024-01-02' }
          - { order_id: 3, customer_id: 'C', subtotal: 30.0, tax_paid: 3.0, order_total: 33.0, order_date: '2024-01-03' }
      - input: this
        rows:
          - { order_id: 1, customer_id: 'A', subtotal: 10.0, tax_paid: 1.0, order_total: 11.0, order_date: '2024-01-01' }
    expect:
      rows:
        - { order_id: 1, customer_id: 'A', subtotal: 10.0, tax_paid: 1.0, order_total: 11.0, order_date: '2024-01-01' }
        - { order_id: 2, customer_id: 'B', subtotal: 20.0, tax_paid: 2.0, order_total: 22.0, order_date: '2024-01-02' }
        - { order_id: 3, customer_id: 'C', subtotal: 30.0, tax_paid: 3.0, order_total: 33.0, order_date: '2024-01-03' } ```

**Comment by eliasdefaria** [comment]
@matt-winkler are you on `0.2.10` of VSCE? Your LSP version might be using an older version of the binary.

I'm going to close this ticket since the issue is fixed for Fusion compilation. Just need to make sure it's rolled out to VSCE.

**Comment by matt-winkler** [comment]
@eliasdefaria yep I'm on that version of the LSP:

```
dbt Extension version: 0.2.10
This version of the dbt extension is configured to use dbt LSP version 2.0.0-beta.37
LSP path: /Users/matt-winkler/Library/Application Support/Cursor/User/globalStorage/dbtlabsinc.dbt/bin/dbt-lsp
Current LSPs in this workspace:
  - /Users/matt-winkler/repos/jaffle-fusion
    - status: running
    - LSP version: 2.0.0-beta.37
```

**Comment by igorferst** [comment]
Hello! I'm still seeing this problem with VSCE 0.2.13 and LSP 2.0.0-beta.56 - is that expected?

```
dbt Extension version: 0.2.13
This version of the dbt extension is configured to use dbt LSP version 2.0.0-beta.56
LSP path: /Users/igor.ferst/Library/Application Support/Code/User/globalStorage/dbtlabsinc.dbt/bin/dbt-lsp
Current LSPs in this workspace:
  - /Users/igor.ferst/REDACTED
    - status: running
    - LSP version: 2.0.0-beta.56
```

**Comment by igorferst** [comment]
Hi @eliasdefaria, can you tell me how to upgrade the LSP? Selecting "Reinstall dbt LSP" doesn't do it, it keeps me at `beta.56`.

**Comment by eliasdefaria** [comment]
@igorferst Sorry I should have been more clear. The LSP version is tied to the VS Code version, so you won't be able to upgrade that until we put out a new VSCE version. However, you can try running a compile from the command line with the latest version by:

1. Running `dbtf system update`
2. Running `dbtf compile`

Then if you could share the logs from that, it would be super helpful!

**Comment by igorferst** [comment]
Don't see this problem any more with extension v 0.2.15 and LSP v 2.0.0-preview.2 🎉
